CONTEUDO DA PÁGINA INDEX.PHP
***************************

1 - CABEÇALHO E RODAPE    - HEADER.PHP E FOOTER.PHP

1.1 - CARROSSEL BOOTSTREP


2 - APRESENTAÇÃO DOS PRODUTOS  ( CLIQUE MOSTRA PÁGINA COM DETALHES )
  - FOTOS, DESCRIÇÃO, PREÇO
  - BOTÃO PARA ESCOLHA DE PRODUTO

3 - PERMITE ADICIONAR PRODUTOS AO CARRINHO

4 - PEDE LOGIN ANTES DE CONFIRMAR A COMPRA. CASO NÃO ESTEJA CADASTRADO, VAI PARA A PÁGINA DE CADASTRO

5 - PÁGINA DE CADASTRO, SOMENTE PARA CEP CADASTRADO PARA LOCAL DE ENTREGA.



WWW.BUSCACEP.CORREIOS.COM.BR/SISTEMAS/BUSCACEP



CONTEUDO DA PÁGINA CARRINHO.PHP
*******************************

 - IMAGEM DO PRODUTO, CATEGORIA, PRODUTO, QUANTIDADE, VALOR UNITÁRIO, TOTAL
 - LIMPAR CARRINHO (BOTAO)
 - EXCLUIR PRODUTO (BOTÃO )
 - ATUALIZAR QUANTIDADE E PREÇO ( BOTÃO )
 - CONTINUAR COMPRANDO PARA ADICIONAR MAIS PRODUTOS (BOTÃO) - CHAMA PÁGINA CARDAPIO.PHP

 - BOTÃO FINALIZAR PEDIDO: VAI PARA A PAGINA LOGIN.PHP ONDE TEM DOIS FORMULÁRIOS: LOGIN.PHP E CADASTRACOMPRADOR.PHP E VAI PARA A PÁGINA CONFIRMARPAGAMENTO.PHP

 - CADASTRACOMPRADOR.PHP - SOMENTE EM ÁREAS DE ENTREGA DO SITE.


CATEGORIA DE PRODUTOS CATEGORIA.PHP
***********************************

CONTEUDO DA PÁGINA PRODUTOS.PHP
*******************************

PRODUTOS SIMPLES: EXEMPLOS,  BEBIDAS, PRATOS, SOBREMESAS PARA COMPLEMENTO DO CARDAPIO NO MOMENTO DA COMPRA.



CONTEUDO DA PÁGINA CARDÁPIO.PHP
************************************************

- MENU DE CATEGORIAS NA HORIZONTAL
- CLIQUE NA OPÇÃO MOSTRA OS PRODUTOS RELACIONADOS.

 - SOMENTE PRATOS...




CONTEUDO DA PÁGINA FORMA DE PAGAMENTO ( ADMIN )
***********************************************






